#
# Makefile for webrtc gocv
#
PROG=gocv-view
usage:
	@echo "usage: make [build|run]"

build b:
	go build -o $(PROG) main.go

run r:
	./$(PROG)

kill k:
	pkill $(PROG)

clean:
	rm -f $(PROG)

git-updtae gu:
	cd ..; make gu




